// <auto-generated />
using System;
using HospitalApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201228182742_Malicious patients added")]
    partial class Maliciouspatientsadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Aleksandar",
                            IsDeleted = false,
                            LastName = "Simonovic",
                            Type = 1,
                            WorkingDays = "2020-12-28 11 AM,2020-12-31 04 PM,2021-01-06 03 PM,2021-01-02 12 PM,2021-01-07 11 AM,2021-01-06 02 PM,2021-01-22 01 PM,2021-01-20 04 PM,2021-01-24 04 PM,2021-01-19 02 PM,2021-01-30 12 PM,2021-02-23 02 PM,2021-02-09 04 PM,2021-01-21 12 PM,2021-02-18 03 PM,2021-02-14 11 AM,2021-02-20 02 PM,2021-02-22 04 PM,2021-03-19 10 AM,2021-02-02 04 PM,2021-02-18 01 PM,2021-03-06 03 PM,2021-03-05 02 PM,2021-03-21 11 AM,2021-04-09 10 AM,2021-03-20 04 PM,2021-04-10 11 AM,2021-03-17 03 PM,2021-04-11 11 AM,2021-03-27 03 PM,2021-04-20 10 AM,2021-03-21 03 PM,2021-03-29 04 PM,2021-05-03 11 AM,2021-03-29 11 AM,2021-04-20 11 AM,2021-04-28 11 AM,2021-05-02 03 PM,2021-04-17 11 AM,2021-05-11 04 PM,2021-05-11 10 AM,2021-04-28 11 AM,2021-05-17 11 AM,2021-04-21 01 PM,2021-05-20 02 PM,2021-05-16 10 AM,2021-05-11 03 PM,2021-05-17 12 PM,2021-05-13 03 PM,2021-05-14 03 PM,2021-05-15 01 PM,2021-05-31 10 AM,2021-06-15 12 PM,2021-05-31 11 AM,2021-05-27 12 PM,2021-06-09 03 PM,2021-06-17 10 AM,2021-06-22 02 PM,2021-06-20 03 PM,2021-06-25 01 PM"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dimitrije",
                            IsDeleted = false,
                            LastName = "Mijatovic",
                            Type = 1,
                            WorkingDays = "2020-12-29 03 PM,2021-01-04 12 PM,2021-01-08 12 PM,2021-01-05 11 AM,2021-01-10 10 AM,2021-01-12 10 AM,2021-01-14 01 PM,2021-01-24 04 PM,2021-01-16 12 PM,2021-01-23 01 PM,2021-01-29 10 AM,2021-01-29 04 PM,2021-02-14 02 PM,2021-02-22 04 PM,2021-02-16 02 PM,2021-02-11 02 PM,2021-02-03 11 AM,2021-03-03 02 PM,2021-03-02 03 PM,2021-02-24 04 PM,2021-02-12 01 PM,2021-02-21 03 PM,2021-03-12 02 PM,2021-02-26 01 PM,2021-03-04 01 PM,2021-03-16 01 PM,2021-03-07 04 PM,2021-04-17 02 PM,2021-03-15 01 PM,2021-03-22 11 AM,2021-03-19 01 PM,2021-03-31 10 AM,2021-04-28 12 PM,2021-03-31 10 AM,2021-04-20 01 PM,2021-04-08 02 PM,2021-03-25 02 PM,2021-04-16 03 PM,2021-04-07 02 PM,2021-04-11 10 AM,2021-05-01 02 PM,2021-04-22 12 PM,2021-04-26 01 PM,2021-04-27 02 PM,2021-05-14 02 PM,2021-05-06 03 PM,2021-05-17 10 AM,2021-05-02 12 PM,2021-05-11 10 AM,2021-05-23 02 PM,2021-05-28 10 AM,2021-05-21 02 PM,2021-06-09 01 PM,2021-06-14 01 PM,2021-06-09 02 PM,2021-06-14 03 PM,2021-06-15 01 PM,2021-06-16 12 PM,2021-06-22 01 PM,2021-06-23 02 PM"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Srdjan",
                            IsDeleted = false,
                            LastName = "Tepavcevic",
                            Type = 0,
                            WorkingDays = "2020-12-31 11 AM,2021-01-03 11 AM,2021-01-05 04 PM,2021-01-04 01 PM,2021-01-16 04 PM,2021-01-17 11 AM,2021-01-18 01 PM,2021-01-14 04 PM,2021-01-20 12 PM,2021-01-27 11 AM,2021-02-01 11 AM,2021-01-28 11 AM,2021-02-06 01 PM,2021-02-01 02 PM,2021-02-14 10 AM,2021-01-26 10 AM,2021-03-05 10 AM,2021-02-11 04 PM,2021-03-03 10 AM,2021-02-13 03 PM,2021-03-03 10 AM,2021-03-02 03 PM,2021-03-02 03 PM,2021-03-10 12 PM,2021-03-21 11 AM,2021-03-16 11 AM,2021-04-01 02 PM,2021-03-18 11 AM,2021-03-13 03 PM,2021-03-20 11 AM,2021-04-02 11 AM,2021-04-02 04 PM,2021-04-05 12 PM,2021-04-21 10 AM,2021-04-07 11 AM,2021-04-10 11 AM,2021-04-15 02 PM,2021-04-27 11 AM,2021-04-12 03 PM,2021-05-15 02 PM,2021-04-23 03 PM,2021-05-04 04 PM,2021-05-16 11 AM,2021-04-27 03 PM,2021-05-07 10 AM,2021-05-29 12 PM,2021-05-14 03 PM,2021-05-05 12 PM,2021-05-20 10 AM,2021-06-02 01 PM,2021-05-24 01 PM,2021-06-07 03 PM,2021-06-05 11 AM,2021-06-16 10 AM,2021-06-12 04 PM,2021-06-19 01 PM,2021-06-12 03 PM,2021-06-17 11 AM,2021-06-21 12 PM,2021-06-22 12 PM"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Neven",
                            IsDeleted = false,
                            LastName = "Milakovic",
                            Type = 0,
                            WorkingDays = "2020-12-28 03 PM,2021-01-05 02 PM,2020-12-31 12 PM,2021-01-11 12 PM,2021-01-04 04 PM,2021-01-20 02 PM,2021-01-17 01 PM,2021-01-12 01 PM,2021-01-12 04 PM,2021-02-02 01 PM,2021-02-05 04 PM,2021-02-11 01 PM,2021-02-08 01 PM,2021-02-11 01 PM,2021-02-14 10 AM,2021-02-25 03 PM,2021-02-26 01 PM,2021-02-19 02 PM,2021-03-04 01 PM,2021-03-06 01 PM,2021-03-08 01 PM,2021-03-11 11 AM,2021-03-05 10 AM,2021-03-14 01 PM,2021-03-07 10 AM,2021-02-24 01 PM,2021-03-27 03 PM,2021-03-10 03 PM,2021-03-31 12 PM,2021-03-15 02 PM,2021-04-09 04 PM,2021-04-13 03 PM,2021-03-31 04 PM,2021-04-06 03 PM,2021-04-19 10 AM,2021-04-17 10 AM,2021-03-29 04 PM,2021-04-24 12 PM,2021-04-28 01 PM,2021-05-08 12 PM,2021-04-28 12 PM,2021-05-04 11 AM,2021-05-05 02 PM,2021-05-05 04 PM,2021-05-09 10 AM,2021-05-11 11 AM,2021-05-09 03 PM,2021-05-28 04 PM,2021-05-28 02 PM,2021-05-22 12 PM,2021-05-19 10 AM,2021-06-11 10 AM,2021-06-02 11 AM,2021-06-19 02 PM,2021-06-10 03 PM,2021-06-10 04 PM,2021-06-16 11 AM,2021-06-20 04 PM,2021-06-20 11 AM,2021-06-25 03 PM"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("SpecialistId");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("HospitalApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Address = "Visnjiceva 32, Beograd",
                            FirstName = "admin",
                            IsDeleted = false,
                            LastName = "administratovic",
                            Password = "admin",
                            PhoneNumber = "+3811233212",
                            Role = "Administrator",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CancelledAppointments")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("GeneralPractitionerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("bit");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("GeneralPractitionerId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tomiceva 22, Zrenjanin",
                            FirstName = "Marko",
                            IsDeleted = false,
                            LastName = "Simonovic",
                            Password = "123",
                            PhoneNumber = "+38122555333",
                            Role = "Patient",
                            Username = "maki",
                            Age = 15,
                            CancelledAppointments = 0,
                            Gender = "male",
                            GeneralPractitionerId = 2,
                            IsBlocked = false,
                            IsMalicious = false
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.HasOne("HospitalApp.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Feedback")
                        .HasForeignKey("HospitalApp.Models.Feedback", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Referral")
                        .HasForeignKey("HospitalApp.Models.Referral", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Doctor", "Specialist")
                        .WithMany("Referrals")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasOne("HospitalApp.Models.Administrator", "BlockedBy")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("HospitalApp.Models.Doctor", "GeneralPractitioner")
                        .WithMany("Patients")
                        .HasForeignKey("GeneralPractitionerId");

                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("BlockedBy");

                    b.Navigation("GeneralPractitioner");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.Navigation("BlockedUsers");
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedback");

                    b.Navigation("Referral");
                });
#pragma warning restore 612, 618
        }
    }
}
