// <auto-generated />
using System;
using HospitalApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20201218165343_M5")]
    partial class M5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Aleksandar",
                            IsDeleted = false,
                            LastName = "Simonovic",
                            Type = 1,
                            WorkingDays = "2020-12-19 11 AM,2020-12-28 02 PM,2020-12-28 12 PM,2020-12-21 11 AM,2020-12-29 01 PM,2021-01-12 03 PM,2021-01-01 10 AM,2021-01-08 04 PM,2021-01-07 03 PM,2021-01-07 02 PM,2021-01-13 02 PM,2021-01-28 04 PM,2021-01-18 04 PM,2021-01-21 11 AM,2021-02-01 01 PM,2021-01-15 01 PM,2021-01-24 01 PM,2021-02-01 10 AM,2021-02-14 10 AM,2021-01-26 03 PM,2021-02-13 02 PM,2021-02-12 03 PM,2021-02-25 12 PM,2021-02-03 04 PM,2021-02-24 12 PM,2021-02-20 03 PM,2021-03-15 01 PM,2021-03-29 04 PM,2021-02-27 02 PM,2021-02-23 03 PM,2021-03-26 01 PM,2021-03-07 01 PM,2021-03-15 12 PM,2021-03-20 03 PM,2021-03-03 04 PM,2021-03-16 03 PM,2021-03-24 03 PM,2021-03-31 12 PM,2021-03-23 03 PM,2021-04-15 12 PM,2021-04-15 12 PM,2021-04-06 03 PM,2021-04-04 03 PM,2021-04-18 04 PM,2021-04-19 12 PM,2021-04-15 01 PM,2021-05-01 04 PM,2021-04-04 03 PM,2021-04-26 01 PM,2021-04-25 03 PM,2021-05-04 12 PM,2021-05-16 10 AM,2021-04-30 03 PM,2021-05-11 04 PM,2021-04-25 04 PM,2021-05-01 11 AM,2021-04-27 12 PM,2021-05-21 01 PM,2021-05-29 11 AM,2021-05-25 12 PM,2021-05-20 02 PM,2021-06-02 12 PM,2021-05-22 04 PM,2021-06-06 02 PM,2021-06-11 10 AM,2021-06-08 03 PM,2021-06-12 12 PM"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dimitrije",
                            IsDeleted = false,
                            LastName = "Mijatovic",
                            Type = 1,
                            WorkingDays = "2020-12-25 10 AM,2020-12-19 11 AM,2020-12-22 04 PM,2021-01-07 03 PM,2020-12-29 01 PM,2021-01-03 10 AM,2021-01-16 02 PM,2021-01-20 03 PM,2021-01-11 02 PM,2021-01-15 11 AM,2021-01-04 12 PM,2021-01-17 04 PM,2021-01-29 12 PM,2021-01-13 02 PM,2021-02-05 02 PM,2021-01-29 12 PM,2021-01-20 03 PM,2021-02-13 04 PM,2021-02-11 12 PM,2021-01-31 02 PM,2021-02-13 11 AM,2021-02-24 11 AM,2021-02-08 12 PM,2021-03-08 04 PM,2021-01-31 03 PM,2021-02-20 03 PM,2021-02-23 10 AM,2021-03-08 12 PM,2021-03-01 04 PM,2021-03-13 12 PM,2021-02-21 11 AM,2021-03-18 01 PM,2021-03-05 10 AM,2021-02-28 12 PM,2021-03-28 01 PM,2021-04-03 12 PM,2021-03-27 02 PM,2021-03-04 11 AM,2021-04-13 11 AM,2021-04-09 01 PM,2021-04-04 10 AM,2021-04-21 02 PM,2021-04-30 02 PM,2021-04-08 01 PM,2021-04-15 03 PM,2021-04-18 10 AM,2021-05-04 12 PM,2021-04-30 10 AM,2021-04-18 04 PM,2021-04-21 11 AM,2021-04-19 04 PM,2021-05-17 04 PM,2021-05-08 02 PM,2021-05-06 10 AM,2021-05-23 01 PM,2021-05-18 04 PM,2021-05-05 04 PM,2021-05-21 03 PM,2021-05-19 03 PM,2021-05-29 01 PM,2021-06-02 04 PM,2021-05-13 01 PM,2021-05-28 01 PM,2021-06-02 02 PM,2021-06-07 02 PM,2021-06-10 04 PM,2021-06-09 11 AM"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Srdjan",
                            IsDeleted = false,
                            LastName = "Tepavcevic",
                            Type = 0,
                            WorkingDays = "2020-12-18 11 AM,2020-12-25 01 PM,2020-12-24 04 PM,2021-01-03 03 PM,2020-12-28 03 PM,2021-01-15 03 PM,2021-01-14 12 PM,2021-01-04 04 PM,2021-01-14 11 AM,2021-01-02 10 AM,2021-01-23 04 PM,2021-01-06 12 PM,2021-01-29 02 PM,2021-01-26 02 PM,2021-02-21 12 PM,2021-02-04 10 AM,2021-02-21 02 PM,2021-01-22 12 PM,2021-02-04 02 PM,2021-02-13 03 PM,2021-02-07 11 AM,2021-02-10 12 PM,2021-02-19 01 PM,2021-02-20 01 PM,2021-02-09 11 AM,2021-02-27 12 PM,2021-03-27 03 PM,2021-02-18 10 AM,2021-03-12 10 AM,2021-03-01 03 PM,2021-02-26 10 AM,2021-03-19 11 AM,2021-03-22 04 PM,2021-03-15 03 PM,2021-04-03 10 AM,2021-03-19 12 PM,2021-04-02 12 PM,2021-04-05 12 PM,2021-03-22 12 PM,2021-03-31 01 PM,2021-04-10 02 PM,2021-03-27 04 PM,2021-04-18 12 PM,2021-04-17 01 PM,2021-04-08 03 PM,2021-05-08 11 AM,2021-04-15 03 PM,2021-05-02 03 PM,2021-04-18 04 PM,2021-04-11 04 PM,2021-05-03 10 AM,2021-05-19 12 PM,2021-05-01 03 PM,2021-05-17 02 PM,2021-05-30 10 AM,2021-05-17 11 AM,2021-05-08 01 PM,2021-05-13 02 PM,2021-06-02 10 AM,2021-06-02 11 AM,2021-05-26 04 PM,2021-05-19 03 PM,2021-06-07 01 PM,2021-06-01 12 PM,2021-06-12 11 AM,2021-06-10 12 PM,2021-06-15 03 PM"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("SpecialistId");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("HospitalApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Address = "Visnjiceva 32, Beograd",
                            FirstName = "admin",
                            IsDeleted = false,
                            LastName = "administratovic",
                            Password = "admin",
                            PhoneNumber = "+3811233212",
                            Role = "Administrator",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.Property<int?>("AdministratorId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("GeneralPractitionerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.HasIndex("AdministratorId");

                    b.HasIndex("GeneralPractitionerId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tomiceva 22, Zrenjanin",
                            FirstName = "Marko",
                            IsDeleted = false,
                            LastName = "Simonovic",
                            Password = "123",
                            PhoneNumber = "+38122555333",
                            Role = "Patient",
                            Username = "maki",
                            Age = 15,
                            Gender = "male",
                            GeneralPractitionerId = 2,
                            IsBlocked = false
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.HasOne("HospitalApp.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Feedback")
                        .HasForeignKey("HospitalApp.Models.Feedback", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Referral")
                        .HasForeignKey("HospitalApp.Models.Referral", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Doctor", "Specialist")
                        .WithMany("Referrals")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasOne("HospitalApp.Models.Administrator", "BlockedBy")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("AdministratorId");

                    b.HasOne("HospitalApp.Models.Doctor", "GeneralPractitioner")
                        .WithMany("Patients")
                        .HasForeignKey("GeneralPractitionerId");

                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("BlockedBy");

                    b.Navigation("GeneralPractitioner");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.Navigation("BlockedUsers");
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedback");

                    b.Navigation("Referral");
                });
#pragma warning restore 612, 618
        }
    }
}
