// <auto-generated />
using System;
using HospitalApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210104131006_Identity added for Referrals")]
    partial class IdentityaddedforReferrals
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CancellationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Aleksandar",
                            IsDeleted = false,
                            LastName = "Simonovic",
                            Type = 1,
                            WorkingDays = "2021-01-04 12 PM,2021-01-13 12 PM,2021-01-08 04 PM,2021-01-23 12 PM,2021-01-22 01 PM,2021-01-16 03 PM,2021-01-17 12 PM,2021-01-30 03 PM,2021-01-21 04 PM,2021-02-08 02 PM,2021-02-02 04 PM,2021-01-30 01 PM,2021-01-25 02 PM,2021-02-21 11 AM,2021-02-02 04 PM,2021-02-17 02 PM,2021-02-13 11 AM,2021-02-19 10 AM,2021-02-27 03 PM,2021-03-09 10 AM,2021-03-08 12 PM,2021-03-04 04 PM,2021-02-22 10 AM,2021-03-17 11 AM,2021-03-10 12 PM,2021-04-06 10 AM,2021-03-18 04 PM,2021-03-24 03 PM,2021-03-19 10 AM,2021-04-02 03 PM,2021-04-14 10 AM,2021-03-24 01 PM,2021-05-02 03 PM,2021-04-30 04 PM,2021-04-07 01 PM,2021-04-04 02 PM,2021-04-28 04 PM,2021-05-07 04 PM,2021-04-17 12 PM,2021-04-30 02 PM,2021-05-06 01 PM,2021-04-28 02 PM,2021-05-11 10 AM,2021-04-29 03 PM,2021-05-21 04 PM,2021-05-27 01 PM,2021-06-03 02 PM,2021-05-23 12 PM,2021-05-22 03 PM,2021-06-01 11 AM,2021-06-03 03 PM,2021-06-06 02 PM,2021-06-12 03 PM,2021-06-14 04 PM,2021-06-24 03 PM,2021-06-21 12 PM,2021-06-21 02 PM,2021-06-28 10 AM,2021-06-19 02 PM,2021-07-02 03 PM"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Dimitrije",
                            IsDeleted = false,
                            LastName = "Mijatovic",
                            Type = 1,
                            WorkingDays = "2021-01-10 02 PM,2021-01-10 12 PM,2021-01-18 12 PM,2021-01-21 02 PM,2021-01-11 03 PM,2021-01-23 04 PM,2021-01-30 11 AM,2021-01-21 11 AM,2021-02-02 02 PM,2021-01-20 12 PM,2021-02-06 10 AM,2021-02-05 01 PM,2021-02-11 03 PM,2021-02-21 01 PM,2021-02-18 04 PM,2021-02-24 11 AM,2021-02-09 01 PM,2021-02-16 11 AM,2021-02-26 01 PM,2021-02-26 02 PM,2021-03-09 04 PM,2021-02-23 01 PM,2021-03-09 12 PM,2021-03-20 04 PM,2021-03-16 03 PM,2021-04-06 10 AM,2021-04-08 04 PM,2021-03-31 03 PM,2021-03-30 02 PM,2021-04-01 02 PM,2021-03-27 12 PM,2021-04-05 01 PM,2021-04-23 11 AM,2021-04-07 02 PM,2021-04-04 10 AM,2021-05-08 10 AM,2021-05-06 02 PM,2021-03-29 11 AM,2021-04-24 02 PM,2021-04-28 12 PM,2021-05-01 03 PM,2021-05-19 04 PM,2021-05-27 01 PM,2021-05-23 03 PM,2021-05-23 04 PM,2021-05-31 01 PM,2021-05-16 04 PM,2021-05-27 01 PM,2021-06-05 03 PM,2021-05-16 12 PM,2021-06-16 02 PM,2021-06-15 02 PM,2021-06-21 04 PM,2021-05-29 03 PM,2021-06-05 11 AM,2021-06-21 02 PM,2021-06-11 01 PM,2021-07-01 11 AM,2021-06-24 03 PM,2021-07-02 03 PM"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Srdjan",
                            IsDeleted = false,
                            LastName = "Tepavcevic",
                            Type = 0,
                            WorkingDays = "2021-01-16 01 PM,2021-01-13 03 PM,2021-01-12 03 PM,2021-01-18 12 PM,2021-01-11 12 PM,2021-01-15 02 PM,2021-01-25 01 PM,2021-01-21 11 AM,2021-01-21 12 PM,2021-01-30 10 AM,2021-02-19 10 AM,2021-02-20 11 AM,2021-02-24 01 PM,2021-02-10 04 PM,2021-02-09 10 AM,2021-01-28 03 PM,2021-02-15 10 AM,2021-02-13 12 PM,2021-03-06 04 PM,2021-02-19 03 PM,2021-03-20 10 AM,2021-03-08 02 PM,2021-04-04 12 PM,2021-04-02 02 PM,2021-03-26 04 PM,2021-03-12 04 PM,2021-03-10 10 AM,2021-03-12 11 AM,2021-04-05 02 PM,2021-04-04 11 AM,2021-04-03 04 PM,2021-04-14 03 PM,2021-05-03 04 PM,2021-04-23 10 AM,2021-04-17 11 AM,2021-04-30 10 AM,2021-05-02 03 PM,2021-05-11 01 PM,2021-04-09 01 PM,2021-05-20 02 PM,2021-05-24 03 PM,2021-05-09 10 AM,2021-05-15 03 PM,2021-05-14 01 PM,2021-05-22 01 PM,2021-05-12 04 PM,2021-05-10 10 AM,2021-05-22 03 PM,2021-05-25 02 PM,2021-05-30 04 PM,2021-05-22 02 PM,2021-05-21 03 PM,2021-06-17 01 PM,2021-05-26 03 PM,2021-06-21 11 AM,2021-06-26 12 PM,2021-06-26 03 PM,2021-06-27 04 PM,2021-06-21 11 AM,2021-07-01 03 PM"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Neven",
                            IsDeleted = false,
                            LastName = "Milakovic",
                            Type = 0,
                            WorkingDays = "2021-01-04 04 PM,2021-01-10 10 AM,2021-01-20 01 PM,2021-01-09 10 AM,2021-01-24 03 PM,2021-01-28 01 PM,2021-01-26 01 PM,2021-01-23 01 PM,2021-01-25 12 PM,2021-01-26 12 PM,2021-01-31 10 AM,2021-02-19 11 AM,2021-02-09 11 AM,2021-02-13 03 PM,2021-02-25 02 PM,2021-02-03 03 PM,2021-02-25 12 PM,2021-02-17 02 PM,2021-02-27 04 PM,2021-03-09 12 PM,2021-03-21 12 PM,2021-03-04 01 PM,2021-03-29 03 PM,2021-03-11 01 PM,2021-03-14 10 AM,2021-03-15 01 PM,2021-03-28 10 AM,2021-03-13 10 AM,2021-03-20 10 AM,2021-04-10 04 PM,2021-04-14 03 PM,2021-04-14 02 PM,2021-04-24 11 AM,2021-04-11 02 PM,2021-04-16 04 PM,2021-05-07 01 PM,2021-05-02 12 PM,2021-05-05 10 AM,2021-04-15 11 AM,2021-04-24 03 PM,2021-04-19 11 AM,2021-05-02 03 PM,2021-05-28 01 PM,2021-04-23 03 PM,2021-05-06 01 PM,2021-05-02 02 PM,2021-05-17 02 PM,2021-05-22 01 PM,2021-06-15 04 PM,2021-06-02 12 PM,2021-05-29 04 PM,2021-06-07 11 AM,2021-05-31 01 PM,2021-06-23 10 AM,2021-06-15 02 PM,2021-06-25 01 PM,2021-06-18 02 PM,2021-06-25 04 PM,2021-06-29 12 PM,2021-07-02 04 PM"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.HasIndex("SpecialistId");

                    b.ToTable("Referral");
                });

            modelBuilder.Entity("HospitalApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMalicious")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.ToTable("Administrator");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Address = "Visnjiceva 32, Beograd",
                            FirstName = "admin",
                            IsBlocked = false,
                            IsMalicious = false,
                            LastName = "administratovic",
                            Password = "admin",
                            PhoneNumber = "+3811233212",
                            Role = "Administrator",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasBaseType("HospitalApp.Models.User");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CancelledAppointments")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("GeneralPractitionerId")
                        .HasColumnType("int");

                    b.HasIndex("GeneralPractitionerId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Tomiceva 22, Zrenjanin",
                            FirstName = "Marko",
                            IsBlocked = false,
                            IsMalicious = false,
                            LastName = "Simonovic",
                            Password = "123",
                            PhoneNumber = "+38122555333",
                            Role = "Patient",
                            Username = "maki",
                            Age = 15,
                            CancelledAppointments = 0,
                            Gender = "male",
                            GeneralPractitionerId = 2
                        });
                });

            modelBuilder.Entity("HospitalApp.Models.Appointment", b =>
                {
                    b.HasOne("HospitalApp.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Feedback", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Feedback")
                        .HasForeignKey("HospitalApp.Models.Feedback", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HospitalApp.Models.Referral", b =>
                {
                    b.HasOne("HospitalApp.Models.Patient", "Patient")
                        .WithOne("Referral")
                        .HasForeignKey("HospitalApp.Models.Referral", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HospitalApp.Models.Doctor", "Specialist")
                        .WithMany("Referrals")
                        .HasForeignKey("SpecialistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Specialist");
                });

            modelBuilder.Entity("HospitalApp.Models.Administrator", b =>
                {
                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Administrator", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.HasOne("HospitalApp.Models.Doctor", "GeneralPractitioner")
                        .WithMany("Patients")
                        .HasForeignKey("GeneralPractitionerId");

                    b.HasOne("HospitalApp.Models.User", null)
                        .WithOne()
                        .HasForeignKey("HospitalApp.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("GeneralPractitioner");
                });

            modelBuilder.Entity("HospitalApp.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Patients");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("HospitalApp.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Feedback");

                    b.Navigation("Referral");
                });
#pragma warning restore 612, 618
        }
    }
}
